Add privacy consideration section about Multistatus Correlation.
w3c/vc-bitstring-status-list pull request #117
Opened 2023-12-29 22:13 UTC by msporny

This PR is an attempt to address issue #86 by adding a privacy considerations section about Multistatus Correlation.

2023-12-30 16:05 UTC, David-Chadwick requested changes
I think this explanation is still rather vague and not that enlightening to people.
For example, why would an entity appear in a status list at different points in time with different statuses?

2023-12-30 16:05 UTC, David-Chadwick commented on index.html
> +contact an entity based on that information, whose current status is known, in
```suggestion
contact an entity whose current status is known, and then based on that information
```

2023-12-30 16:05 UTC, David-Chadwick commented on index.html
> +an attempt to phish more lucrative information from them using data gleaned
```suggestion
attempt to phish more lucrative information from it using data gleaned
```

2023-12-30 20:47 UTC, dlongley approved these changes
+1 to David's grammatical fixes.

2024-01-02 16:46 UTC, TallTed approved these changes
with @David-Chadwick's previously suggested changes

2024-01-02 20:39 UTC, msporny commented on index.html
> +from the status list over time.
```suggestion
information to an attacker. Given such information, a phishing operation could
predict what the next step of a business process is and then preemptively
contact an entity whose current status is known. Then, based on that 
information, they could attempt to phish more lucrative information from 
the target using data gleaned from the status list over time.
```

2024-01-03 21:39 UTC, KDean-GS1 approved these changes

2024-01-03 22:28 UTC, longpd approved these changes

2024-01-13 20:28 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-01-13 20:28 UTC, merged