Rename "herd" to "group" privacy.
w3c/vc-bitstring-status-list pull request #121
Opened 2023-12-30 16:16 UTC by msporny

This is a simple editorial rename of "herd privacy" to "group privacy". Some in the group find the term "herd", when applied to humans, as mildly offensive. The counter argument is that we're all animals too. :P

The term "group privacy" is used as synonymous to "herd privacy" in much of the literature I found during a quick search on to see if this would create confusion among readers that go searching for literature. "Group privacy" also wins the [Google trends search](https://trends.google.com/trends/explore?date=all&q=herd%20privacy,group%20privacy&hl=en) for the past 20-ish years.

2023-12-30 16:36 UTC, David-Chadwick approved these changes

2023-12-30 18:06 UTC, kimdhamilton commented
😢 RIP herd

2023-12-30 20:23 UTC, msporny commented
> 😢 RIP herd

Don't worry, we have a `FilthyAnimalStatusList` in the works. It'll preserve all the best parts of "herd privacy" and won't differentiate between animals or humans, which clearly increases the privacy characteristics of the solution.

2023-12-30 20:46 UTC, dlongley approved these changes

2023-12-31 09:09 UTC, iherman approved these changes

2024-01-02 19:07 UTC, TallTed requested changes
trivial removal of an extra space character

2024-01-02 19:07 UTC, TallTed commented on index.html
> +population size ensures an adequate amount of group  privacy in the average case.
```suggestion
population size ensures an adequate amount of group privacy in the average case.
```

2024-01-02 19:09 UTC, TallTed requested changes
change `1-1` to `one-to-one`

2024-01-02 19:09 UTC, TallTed commented on index.html
>  another a 1-1 mapping by using a different cryptographic key for every credential
Spotted just as I submitted the other review...
```suggestion
unique status list per credential issued in order to establish a one-to-one mapping to track
when a <a>verifier</a> processes a specific credential. Similarly, they could establish
another a one-to-one mapping by using a different cryptographic key for every credential
```

2024-01-02 22:02 UTC, brianorwhatever approved these changes

2024-01-02 22:29 UTC, TallTed approved these changes

2024-01-03 22:25 UTC, KDean-GS1 approved these changes
Following the herd in approving this change. Moooooooo...

2024-01-10 16:48 UTC, andresuribe87 approved these changes

2024-01-10 17:14 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-10-vcwg#section3-6) on 2024-01-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.6. Rename "herd privacy" to "group privacy". (pr vc-bitstring-status-list#121)

_See github pull request [vc-bitstring-status-list#121](https://github.com/w3c/vc-bitstring-status-list/pull/121)._




**Manu Sporny:** renames herd privacy to group privacy.  

</details>

2024-01-13 21:03 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-01-13 21:03 UTC, merged