Add at risk issue marker regarding multibit status entries.
w3c/vc-bitstring-status-list pull request #123
Opened 2023-12-30 20:05 UTC by msporny

This PR is an attempt at addressing [some comments](https://github.com/w3c/vc-bitstring-status-list/issues/73#issuecomment-1872490184) in issue #73 by marking the multibit status entry feature as at risk. The PR makes it such that implementers don't have to implement the feature to have a conforming processor, but allows implementations that need the feature to implement it in an interoperable fashion.

2023-12-30 20:49 UTC, dlongley approved these changes

2024-01-02 16:53 UTC, TallTed requested changes

2024-01-02 16:53 UTC, TallTed commented on CONTRIBUTING.md
> +identify all  contributors in the pull request comment.
```suggestion
identify all contributors in the pull request comment.
```

2024-01-02 16:53 UTC, TallTed commented on CONTRIBUTING.md
> +To add a contributor (other than yourself, that's automatic), mark them one per
```suggestion
To add a contributor (other than yourself; that's automatic), mark them one per
```

2024-01-02 16:53 UTC, TallTed commented on index.html
> +implements the second option.
```suggestion
The Working Group is currently seeking implementer feedback regarding the
utility of bitstring entries that have sizes greater than one. Supporting
such entries adds complexity to the solution, and it's not clear whether there
is enough of an implementation community to support the feature. The WG is
considering three options: (1) require conforming implementations to support
the feature; (2) allow implementations to optionally support the feature; or
(3) remove the feature. At present, the specification implements option (2).
```

2024-01-02 22:06 UTC, brianorwhatever approved these changes

2024-01-10 16:49 UTC, andresuribe87 approved these changes

2024-01-10 17:14 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-01-10-vcwg#section3-7) on 2024-01-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. Add at risk issue marker regarding multibit status entries. (pr vc-bitstring-status-list#123)

_See github pull request [vc-bitstring-status-list#123](https://github.com/w3c/vc-bitstring-status-list/pull/123)._




**Manu Sporny:** adding an at risk marker to the multiple status list feature.  
… if there are insufficient implementors of this feature it will be removed.  
… we will need a test suite for it as well as implementations.  

> *Chris Abernethy:* I believe we intend to implement it.

</details>

2024-01-13 21:22 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-01-13 21:22 UTC, merged