Explicitly allow `issuer` to be different between VC and BSLC.
w3c/vc-bitstring-status-list pull request #129
Opened 2024-01-14 16:23 UTC by msporny

This PR is an attempt to address issue #124 by explicitly noting that the `issuer` value for a `BitstringStatusListCredential` MAY be different from the `issuer` value of the associated VC.

/cc @jchartrand

2024-01-14 19:08 UTC, dlongley approved these changes

2024-01-15 20:06 UTC, KDean-GS1 approved these changes

2024-01-16 16:56 UTC, brianorwhatever approved these changes

2024-01-16 22:48 UTC, TallTed requested changes
Editorial, markup & grammar

2024-01-16 22:48 UTC, TallTed commented on index.html
> +`BitstringStatusListCredential`.
```suggestion
<a>Issuers</a> and <a>verifiers</a> are advised that the `issuer` of a
<a>verifiable credential</a> and the `issuer` of an associated
`BitstringStatusListCredential` might not be the same. There are technical,
legal, institutional, and political reasons that might make it appropriate
to separate the authority over the original credential from the authority to
revoke such a credential. Therefore, the `issuer` value of a <a>verifiable
credential</a> containing a `BitstringStatusListEntry` MAY be different from
the `issuer` value of a `BitstringStatusListCredential`.
```

2024-01-16 23:20 UTC, dmitrizagidulin approved these changes
👍 
Thanks @msporny, that's perfect!

2024-01-21 23:09 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-01-21 23:09 UTC, merged