Add normative statements related to caching of status list VCs.
w3c/vc-bitstring-status-list pull request #153
Opened 2024-03-24 16:55 UTC by msporny

This PR is an attempt to address issue #144 by providing normative guidance to both issuers and verifiers on publishing, retrieval, and caching behaviour.

2024-03-24 18:20 UTC, dlongley approved these changes

2024-03-25 04:28 UTC, brianorwhatever approved these changes

2024-03-25 08:33 UTC, iherman reviewed
The Oblivious HTTP spec that is referred to (possibly elsewhere, too, not only in the proposed changes) is set to expire at the end of February. There should be a valid reference.

2024-03-25 08:41 UTC, David-Chadwick approved these changes

2024-03-26 17:09 UTC, TallTed requested changes

2024-03-30 15:18 UTC, msporny commented on index.html
> +through [[[?OHTTP]]], a content distribution network that is not operated by the
```suggestion
through [[[OHTTP]]], a content distribution network that is not operated by the
```

2024-03-30 15:24 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-03-30 15:25 UTC, merged