Clarify normative text around randomness of list index.
w3c/vc-bitstring-status-list pull request #154
Opened 2024-03-24 18:34 UTC by msporny

This PR is an attempt to address issue #149 by being more specific about the randomization requirements for the status list index.

2024-03-25 04:28 UTC, dlongley approved these changes

2024-03-25 04:28 UTC, brianorwhatever approved these changes

2024-03-25 08:35 UTC, iherman approved these changes

2024-03-25 09:22 UTC, David-Chadwick reviewed
Why is this a SHOULD and not a MUST?

2024-03-25 16:20 UTC, decentralgabe approved these changes

2024-03-26 15:38 UTC, Wind4Greg approved these changes

2024-03-26 18:48 UTC, TallTed requested changes

2024-03-26 18:48 UTC, TallTed commented on index.html
> +group.
```suggestion
SHOULD assign indexes randomly, such that inferences — such as the recency
of the assignment or the size of the group — cannot be easily drawn from
that position.
```

2024-03-30 18:22 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-03-30 18:22 UTC, merged