Add section on media types
w3c/vc-bitstring-status-list pull request #92
Opened 2023-10-31 16:49 UTC by OR13

Addresses:

- https://github.com/w3c/vc-bitstring-status-list/issues/78

2023-11-09 22:05 UTC, TallTed requested changes

2023-11-09 22:05 UTC, TallTed commented on index.html
> +      SD-JWT might have content-type <code>application/vc+ld+json+sd-jwt</code>.
`application/vc+ld+json+sd-jwt` should not exist. `application/sd-jwt` may contain `application/vc+ld+json`.
```suggestion
      SD-JWT might have content-type <code>application/sd-jwt</code>.
```

2023-11-09 22:05 UTC, TallTed commented on index.html
> +      <code>application/ld+json</code>, <code>application/json</code> or <code>application/sd-jwt</code>.
```suggestion
      Some implementations might choose to support less specific media types such as
      <code>application/ld+json</code> or <code>application/json</code>.
```

2023-11-09 22:05 UTC, TallTed commented on index.html
> +      status code to signal if they do not support the requested media type.
```suggestion
      status code to signal that they do not support the requested media type.
```

2023-11-09 22:05 UTC, TallTed commented on index.html
> +Implementations SHOULD consume / assign indexes randomly.
```suggestion
Implementations SHOULD consume and/or assign indexes randomly. 
```

2023-12-27 21:02 UTC, msporny approved these changes

2023-12-27 21:03 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-12-27 21:03 UTC, merged